version: '3.8'

services:
  backend:
    image: sergey15g/foodgramnew_backend:latest
    container_name: foodgram_backend
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
      POSTGRES_DB: django_db
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    volumes:
      - backend_data:/app
    depends_on:
      - nginx

  frontend:
    image: sergey15g/foodgramnew_frontend:latest
    container_name: foodgram_frontend
    environment:
      NODE_ENV: production
    volumes:
      - frontend_data:/app
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: foodgram_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - backend_static:/backend_static
      - frontend_data:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend

volumes:
  backend_data:
  frontend_data:
  backend_static:
