version: '3.8'

services:
  backend:
    image: sergey15g/foodgramnew_backend:latest
    container_name: backend
    env_file:
      - .env
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
      POSTGRES_DB: django_db
      DB_HOST: "${DB_HOST}"
      DB_PORT: 5432
      SECRET_KEY: "${SECRET_KEY}"
      DEBUG: "${DEBUG}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
    depends_on:
      - postgres

  frontend:
    image: sergey15g/foodgramnew_frontend:latest
    container_name: frontend
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

  postgres:
    image: postgres:13.10
    container_name: postgres
    environment:
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
      POSTGRES_DB: django_db
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_value:
  media_value:
  data_value: