# Generated by Django 4.2.14 on 2024-09-15 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopping_cart", "0003_alter_shoppingcart_recipe_alter_shoppingcart_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShoppingCart",
        ),
    ]
