# Generated by Django 4.2.14 on 2024-09-15 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0002_alter_tag_name_alter_tag_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тэг", "verbose_name_plural": "Тэги"},
        ),
    ]
