# Generated by Django 4.2.14 on 2024-07-22 18:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_subscription"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="cooking_time",
            new_name="cooking_duration",
        ),
    ]
