# Generated by Django 4.2.14 on 2024-07-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_rename_cooking_duration_recipe_cooking_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="measurement_unit",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="recipeingredient",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
