# Generated by Django 4.2.14 on 2024-08-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("recipes", "0007_favorite_favorite_unique_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                related_name="recipes", to="tags.tag"
            ),
        ),
    ]
