# Generated by Django 4.2.14 on 2024-09-15 19:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "recipes",
            "0010_alter_recipe_author_alter_recipe_cooking_time_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзины",
            },
        ),
        migrations.AlterModelOptions(
            name="favorite",
            options={
                "verbose_name": "Избранное",
                "verbose_name_plural": "Избранные",
            },
        ),
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "verbose_name": "Ингридиент",
                "verbose_name_plural": "Ингридиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={
                "verbose_name": "Ингридиент рецепта",
                "verbose_name_plural": "Ингридиенты рецептов",
            },
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
        migrations.AlterUniqueTogether(
            name="subscription",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_favorited",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="is_in_shopping_cart",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="measurement_unit",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="name",
        ),
        migrations.AddField(
            model_name="subscription",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes_subscribers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1,
                        message="Время приготовления не может быть меньше 1 минуты",
                    ),
                    django.core.validators.MaxValueValidator(
                        10000,
                        message="Время приготовления не может превышать 10000 минут",
                    ),
                ],
                verbose_name="Время готовки",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes_subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Юзверь",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                fields=("user", "author"),
                name="unique_subscription_recipes",
            ),
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes_in_shopping_cart",
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
        migrations.AddField(
            model_name="shoppingcart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes_shopping_cart",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="recipe",
        ),
        migrations.AddConstraint(
            model_name="shoppingcart",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_shopping_cart"
            ),
        ),
    ]
