# Generated by Django 4.2.14 on 2024-09-17 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0011_shoppingcart_alter_favorite_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="amount",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Количество не может быть меньше 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        10000, message="Количество не может превышать 10000"
                    ),
                ],
                verbose_name="Кол-во",
            ),
        ),
    ]
