# Generated by Django 4.2.14 on 2024-09-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0003_alter_tag_options"),
        ("recipes", "0012_alter_recipeingredient_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="recipes",
                to="tags.tag",
                verbose_name="Тэги",
            ),
        ),
    ]
