# Generated by Django 4.2.14 on 2024-09-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0003_alter_tag_options"),
        ("recipes", "0013_alter_recipe_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                related_name="recipes", to="tags.tag", verbose_name="Тэги"
            ),
        ),
    ]
