# Generated by Django 4.2.14 on 2024-09-26 20:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0016_delete_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeingredient",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recipes.ingredient",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Количество не может быть меньше 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        10000, message="Количество не может превышать 10000"
                    ),
                ],
                verbose_name="Ингридиент",
            ),
        ),
    ]
